# Generated by Django 2.2.5 on 2020-01-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='cleanliness',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
